version: '3.8'

services:
  base-de-datos:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: info
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - microservices_network

  microservicio-estudiante:
    build:
      context: ./estudiante
    ports:
      - "8081:8080"
    depends_on:
      - base-de-datos
    networks:
      - microservices_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://base-de-datos:5432/info
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  microservicio-evaluacion:
    build:
      context: ./evaluacion
    ports:
      - "8082:8080"
    depends_on:
      - base-de-datos
      - microservicio-estudiante
    networks:
      - microservices_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://base-de-datos:5432/info
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      ESTUDIANTE_SERVICE_URL: http://microservicio-estudiante:8080/estudiantes/

networks:
  microservices_network:
    driver: bridge

volumes:
  db_data:
